### PR TITLE
added android support and local events

### PR DESCRIPTION
**Pull request by ghost**
iOS uses the NSNotificationCenter for eventing
android uses the LocalBroadcastManager for eventing
results and events are now wrapped by objects, this is for android's benefit
bumped version number to 0.2.0

### CODE REVIEW

**Comment by artemyarulin** [comment]
Hi! Thanks a lot for the pull requests.

Couple of questions:
1. Package.json at the end, any reason for that?

```
  "gitHead": "a49371aa394aa56724e948c5a4780688cc80a9a0",
  "bugs": {
    "url": "https://github.com/artemyarulin/react-native-eval/issues"
  },
  "homepage": "https://github.com/artemyarulin/react-native-eval#readme",
  "_id": "react-native-eval@0.1.0",
  "_shasum": "f016db657efbf483f92d006324f0bb2d5b64a4e1",
  "_from": "../react-native-eval",
  "_resolved": "file:../react-native-eval"
```
1. NSNotificationCenter/LocalBroadcastManager - what the benefits of this? Can't we continue with callbacks?
2. I have no ideas about Android development but `gradle-wrapper.jar` binary file, is this a required file?
3. iOS podspec now using subspec `core`, any benefits for this? Not sure that this project gonna be ever spitted in multiple specs
4. `react_native_evalTests.m removed`, not good, not good

Thanks in advance!

**Comment by ghost** [comment]
1. removed the package.json junk
2. NSNotificationCenter/LocalBroadcastManager.
   Using the built-in pub/sub solutions provides less overhead and complexity in the NativeModule.  These solutions provide thread-safety, efficiency, etc.  Also, the goal here is to integrate into current apps, so I wanted to minimize the footprint.
3. yes, the gradle-wrapper.jar is typically checked in for android dev.  :(
4. fixed the spec
5. brought in the original project, tests and all.

**Comment by artemyarulin** [comment]
Awesome, thanks!

**Comment by artemyarulin** [comment]
Just wonder - why do you need this?:) 

Originally I've created this in order to support ClojureScript and call it from native side, what is your use case?

**Comment by ghost** [comment]
I need a cross-platform library, and I like the idea of using a higher level language than C.

**Pull request merged**
